services:
  postgres:
    image: postgres:latest
    container_name: pg_read_adviser
    environment:
      POSTGRES_DB: read_adviser
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: do8poOcugQ94K1c
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: read_adviser_bot
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: do8poOcugQ94K1c
      POSTGRES_DBNAME: read_adviser
      POSTGRES_SSLMODE: disable
    restart: unless-stopped

volumes:
  postgres_data: